apiVersion: apps/v1 
kind: Deployment
metadata:
  name: podinfo
  namespace: test
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.app: semver:^1.0
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image:  amadouth/swh-counter1:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name:  http
          containerPort: 9898
          protocol: TCP
  spec:
  containers:
  - name: podinfod
  image: amadouth/swh-counter1:1.0.0 # {"$imagepolicy": "flux-system:podinfo"} 


