apiVersion: apps/v1 
kind: Deployment
metadata:
  name: podinfo
  namespace: test
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image:  amadouth/swh-counters
        resources:
      resources:
        requests:
          memory: "75Mi"
          cpu: "20m"
        limits:
          memory: "150Mi"
          cpu: "200m"
        imagePullPolicy: IfNotPresent
        ports:
        - name:  http
          containerPort: 9898
          protocol: TCP
